#!/bin/bash

getAG() {
  sudo apt-get install -y automake pkg-config libpcre3-dev zlib1g-dev liblzma-dev
  if [ ! -f /usr/local/bin/ag ]; then
    git clone https://github.com/ggreer/the_silver_searcher.git ag
    cd ag
    ./build.sh
    sudo make install
  fi

  if [ -d /home/vagrant/ag ]; then
    rm -rf /home/vagrant/ag
  fi
}

getAG
